### PR TITLE
Wip zip sanitize

### PR DESCRIPTION
**Pull request by dillense**
When importing a CLIF test project as a .zip archive file, possible malicious paths are "sanitized":
1. absolute paths (in case in can happen?)'s root is discarded 
2. paths are normalized (. path elements are discarded, as well as paths sequences like subdir/..)
3. possibly remaining .. path elements are merely dropped

### CODE REVIEW

**Comment by dillense** [comment]
Solves issue [SECURITY-2413](https://issues.jenkins.io/browse/SECURITY-2413)

**Comment by dillense** [comment]
Fixes [SECURITY-2413](https://issues.jenkins.io/browse/SECURITY-2413)

**Comment by daniel-beck** [comment]
What I don't understand about this is why users with Overall/Read permission are able to use this feature. In the case of an instance like https://ci.jenkins.io/ everyone on the internet can upload a file. Why is there no permission check? Is this intentional?

**Comment by dillense** [comment]
Hello Daniel. From what I observe, the Import CLIF archive Link is always active, but if you are not connected and do not have the permission for creating jobs, the import fails (i.e. no file created and no job created).
Now, I agree that the link should not appear in this case, but this point had never been raised before (and I never paid attention to this issue - I'm used to use Jenkins in very restricted/closed environments/networks). Given my observations above, I think there is no security issue there. Please tell me if you observe some writings however.
Sample test files:
- regular CLIF zip archive: [clif-examples-1.zip](https://github.com/jenkinsci/clif-performance-testing-plugin/files/9323769/clif-examples-1.zip)
- malicious zip archive: [ProofOfConceptSEC2413.zip](https://github.com/jenkinsci/clif-performance-testing-plugin/files/9324030/ProofOfConceptSEC2413.zip)

**Pull request merged**
